Database week3
HackYourAssignment/databases-class44 pull request #35
Opened 2023-09-05 14:34 UTC by Hadeel-Mur

2023-09-19 18:31 UTC, ayatalat approved these changes

2023-09-19 18:31 UTC, ayatalat commented on Week3/homework/assignment/1-SQLnormalization.md
> +none of the columns in the provided table violate the First Normal Form (1NF).
wrong answer 
 `dinner_date` has multiple types
  `food_code` , `food_description`  multiple values not atomic

2023-09-19 18:31 UTC, ayatalat commented on Week3/homework/assignment/1-SQLnormalization.md
> +2- What entities do you recognize that could be extracted?
also we can extract 
    member, food, venue, dinner

2023-09-19 18:31 UTC, ayatalat commented on Week3/homework/assignment/1-SQLnormalization.md
> +table2 (dinners) dinner_id, dinner_date, venue_code, food_code.
why do you add venue_code here ?

2023-09-19 18:35 UTC, ayatalat requested changes

2023-09-19 18:35 UTC, ayatalat commented on Week3/homework/assignment/mongo-practice.js
> +const uri = "mongodb+srv://murshedhadeel:<2tQWHrrvGDZdIbYY>@cluster0.asbcayp.mongodb.net/?retryWrites=true&w=majority";
this should be added from env file and read it from it 
you can use a npm package called require("dotenv") checkout here how you can use it https://www.npmjs.com/package/dotenv

2023-09-21 12:03 UTC, Hadeel-Mur commented on Week3/homework/assignment/1-SQLnormalization.md
> +table2 (dinners) dinner_id, dinner_date, venue_code, food_code.
avoiding duplicating venue information (such as venue_description and number_address) for each dinner event. Instead,i reference the venue table using a foreign key (venue_code),

2023-10-31 15:22 UTC, closed without merging